---
- name: Configure users
  import_tasks: users.yml
  tags: users

- name: Configure timezone
  import_tasks: timezone.yml
  tags: timezone

- name: Configure DNS search domains (Netplan-aware)
  import_tasks: dns.yml
  tags: dns

- name: Configure NFS mounts
  import_tasks: nfs.yml
  tags: nfs

- name: Configure local disks
  import_tasks: disks.yml
  tags: disks

- name: Include geerlingguy.firewall role if desired
  import_role:
    name: geerlingguy.firewall
  vars:
    firewall_disable_firewalld: true
  when: firewall_enabled | default(true)

- name: Update packages and reboot if needed
  import_tasks: update.yml
  tags:
    - update
    - never
