---
- name: Merge firewall TCP ports
  set_fact:
    merged_firewall_tcp_ports: >-
      {{ ((common_firewall_rules.tcp | default([])) + (common_firewall_extra_tcp_ports | default([]))) | unique }}

- name: Merge firewall UDP ports
  set_fact:
    merged_firewall_udp_ports: >-
      {{ ((common_firewall_rules.udp | default([])) + (common_firewall_extra_udp_ports | default([]))) | unique }}

- name: Apply firewall using geerlingguy.firewall
  include_role:
    name: geerlingguy.firewall
